### user Sing up endpoint
POST https://query-tickecting-system.onrender.com/users/newuser
Content-Type: application/json

{
        "firstname":"student",
        "lastname":"MERN",
        "email":"MERNmentor@gmail.com",
        "password":"mentor12345",
        "mobile":9025252525,
        "role":"mentor",
        "isActive":false
}
### user Sing in endpoint
POST https://query-tickecting-system.onrender.com/users/login
Content-Type: application/json
  {

     "email":"MERNmentor@gmail.com",
     "password":"mentor12345"

    }
### Get a user Profile endpoint
GET  https://query-tickecting-system.onrender.com/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1FUk5tZW50b3JAZ21haWwuY29tIiwiaWF0IjoxNjg3MzQxOTg1LCJleHAiOjE2ODc1MTQ3ODV9.0obE09NjsmpdHU2qcuvaBZ99VgwudAukbeJNt2V7pmQ

### Get refreshed token 
GET  https://query-tickecting-system.onrender.com/tokens/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1FUk5tZW50b3JAZ21haWwuY29tIiwiaWF0IjoxNjg3MzQxOTg1LCJleHAiOjE2ODc1MTQ3ODV9.0obE09NjsmpdHU2qcuvaBZ99VgwudAukbeJNt2V7pmQ


### Password-Reset Endpoits

POST https://query-tickecting-system.onrender.com/users/reset-password
Content-Type: application/json

{
    "email":"Mern.mentor@gmail.com"
}

### UPDATE New password  Endpoits
PATCH  https://query-tickecting-system.onrender.com/users/reset-password
Content-Type: application/json
{
    "email":"Mern.mentor@gmail.com",
    "pin":"422945",
    "newPassword":"12345"
}
### User Sign out Endpoint
DELETE  https://query-tickecting-system.onrender.com/users/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzMxOTU0NiwiZXhwIjoxNjg3MzIwNDQ2fQ.oHAUIlRi6TeHuO1G9rXfHjpI48kKdylfMcBbotnWM34

###Ticket API

### Add new ticket 
POST https://query-tickecting-system.onrender.com/tickets/addnewticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI
Content-Type: application/json

{
          "category":"Zen-Class Doubt",
          "subCategory":"Code Kata",
          "tags":"node js",
          "preferredLanguage":"Tamil",
          "title":"exampleexampleexample",
          "description":"exampleexampleexample",
         "availableTimefrom":"nil",
          "availableTimetill":"nil"
}

### get users tickets
GET https://query-tickecting-system.onrender.com/tickets/usertickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI

###get users specific tickets
GET https://query-tickecting-system.onrender.com/tickets/gettickets/64918b794dc2f67567b52832
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzMyNjE0MiwiZXhwIjoxNjg3MzI3MDQyfQ.aaQqy399Yjkzi_QJQvMWXXdqP0EvpvdcvYWPEbJL4yg

###Close Tickets
PATCH https://query-tickecting-system.onrender.com/tickets/close-ticket/64918b794dc2f67567b52832
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI

### change ticket status
PUT https://query-tickecting-system.onrender.com/tickets/assign-ticket/64918b794dc2f67567b52832
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI

###Update message in ticket
PUT https://query-tickecting-system.onrender.com/tickets/reply-ticket/64918b794dc2f67567b52832
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI
Content-Type: application/json
       { 
    "message":"hi,hihi",
     "sender":"student"
    }

