### user Sing up endpoint
POST https://query-tickecting-system.onrender.com/users/newuser
Content-Type: application/json

{
        "firstname":"student",
        "lastname":"MERN",
        "email":"mohammed.mi@gmail.com",
        "password":"student12345",
        "mobile":9025252525,
        "role":"student",
        "isActive":false
}
### user Sing in endpoint
POST http://localhost:9000/users/login
Content-Type: application/json

{
   "email":"Mern.mentor@gmail.com",
    "password":"student123"
}

### Get a user Profile endpoint
GET  http://localhost:9000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NjI1OSwiZXhwIjoxNjg3Mjc3MTU5fQ.sHB3d8ocwrXmeOwfI-2a2oGu7If2jHANdcFwxQAoQ3Y

### Get refreshed token 
GET  http://localhost:9000/tokens/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtbWVkaW1yYW4ubWlAZ21haWwuY29tIiwiaWF0IjoxNjg3MjM3NzEyLCJleHAiOjE2ODc0MTA1MTJ9.yLxxmlo1crPOh00HnTgCEyZ3yUhVJWGXiYv64j52Jik


### Password-Reset Endpoits

POST http://localhost:9000/users/reset-password
Content-Type: application/json

{
    "email":"mohammedimran1407.mi@gmail.com"
}

### UPDATE New password  Endpoits
PATCH  http://localhost:9000/users/reset-password
Content-Type: application/json
{
    "email":"mohammedimran1407.mi@gmail.com",
    "pin":"060445",
    "newPassword":"12345"
}
### User Sign out Endpoint
DELETE  http://localhost:9000/users/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NTMyNCwiZXhwIjoxNjg3Mjc2MjI0fQ.3dc8rxHc9UGMjJZ9pw1rb7itcScmSPgqMEHq67Ay5ig

###Ticket API

### Add new ticket 
POST http://localhost:9000/tickets/addnewticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI
Content-Type: application/json

{
          "category":"Zen-Class Doubt",
          "subCategory":"Code Kata",
          "tags":"node js",
          "preferredLanguage":"Tamil",
          "title":"exampleexampleexample",
          "description":"exampleexampleexample",
         "availableTimefrom":"nil",
          "availableTimetill":"nil"
}

### get users tickets
GET http://localhost:9000/tickets/usertickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI

###get users specific tickets
GET http://localhost:9000/tickets/gettickets/64918b794dc2f67567b52832
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI

###Close Tickets
PATCH http://localhost:9000/tickets/close-ticket/64918b794dc2f67567b52832
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI

### change ticket status
PUT http://localhost:9000/tickets/assign-ticket/64918b794dc2f67567b52832
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI

###Update message in ticket
PUT http://localhost:9000/tickets/reply-ticket/64918b794dc2f67567b52832
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcm4ubWVudG9yQGdtYWlsLmNvbSIsImlhdCI6MTY4NzI3NzUxNSwiZXhwIjoxNjg3Mjc4NDE1fQ.IpaUFDzvUOAXuL54YoY7Z7EiyMDCsn22X8zFmo4MWfI
Content-Type: application/json
       { 
    "message":"hi,hihi",
     "sender":"student"
    }

